// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AllInputData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AllInputData.proto</summary>
public static partial class AllInputDataReflection {

  #region Descriptor
  /// <summary>File descriptor for AllInputData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AllInputDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJBbGxJbnB1dERhdGEucHJvdG8ioQEKDEFsbElucHV0RGF0YRITCgtnbG9i",
          "YWxGcmFtZRgBIAEoBRI5Cg5hbGxDbGllbnRJbnB1dBgCIAMoCzIhLkFsbElu",
          "cHV0RGF0YS5BbGxDbGllbnRJbnB1dEVudHJ5GkEKE0FsbENsaWVudElucHV0",
          "RW50cnkSCwoDa2V5GAEgASgFEhkKBXZhbHVlGAIgASgLMgouSW5wdXREYXRh",
          "OgI4ASJsCglJbnB1dERhdGESCgoCaWQYASABKAUSFAoMZ2xvYmFsX2ZyYW1l",
          "GAIgASgFEg4KBmF4aXNfeBgDIAEoAhIOCgZheGlzX3kYBCABKAISDgoGYWN0",
          "aW9uGAUgASgFEg0KBXNwZWVkGAYgASgCKjoKB01vdmVEaXISCAoETm9uZRAA",
          "EgYKAlVwEAESCAoERG93bhACEggKBExlZnQQAxIJCgVSaWdodBAEYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MoveDir), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AllInputData), global::AllInputData.Parser, new[]{ "GlobalFrame", "AllClientInput" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::InputData), global::InputData.Parser, new[]{ "Id", "GlobalFrame", "AxisX", "AxisY", "Action", "Speed" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum MoveDir {
  [pbr::OriginalName("None")] None = 0,
  [pbr::OriginalName("Up")] Up = 1,
  [pbr::OriginalName("Down")] Down = 2,
  [pbr::OriginalName("Left")] Left = 3,
  [pbr::OriginalName("Right")] Right = 4,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AllInputData : pb::IMessage<AllInputData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AllInputData> _parser = new pb::MessageParser<AllInputData>(() => new AllInputData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AllInputData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AllInputDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AllInputData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AllInputData(AllInputData other) : this() {
    globalFrame_ = other.globalFrame_;
    allClientInput_ = other.allClientInput_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AllInputData Clone() {
    return new AllInputData(this);
  }

  /// <summary>Field number for the "globalFrame" field.</summary>
  public const int GlobalFrameFieldNumber = 1;
  private int globalFrame_;
  /// <summary>
  ///标记当前逻辑帧
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GlobalFrame {
    get { return globalFrame_; }
    set {
      globalFrame_ = value;
    }
  }

  /// <summary>Field number for the "allClientInput" field.</summary>
  public const int AllClientInputFieldNumber = 2;
  private static readonly pbc::MapField<int, global::InputData>.Codec _map_allClientInput_codec
      = new pbc::MapField<int, global::InputData>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::InputData.Parser), 18);
  private readonly pbc::MapField<int, global::InputData> allClientInput_ = new pbc::MapField<int, global::InputData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, global::InputData> AllClientInput {
    get { return allClientInput_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AllInputData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AllInputData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (GlobalFrame != other.GlobalFrame) return false;
    if (!AllClientInput.Equals(other.AllClientInput)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (GlobalFrame != 0) hash ^= GlobalFrame.GetHashCode();
    hash ^= AllClientInput.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (GlobalFrame != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(GlobalFrame);
    }
    allClientInput_.WriteTo(output, _map_allClientInput_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (GlobalFrame != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(GlobalFrame);
    }
    allClientInput_.WriteTo(ref output, _map_allClientInput_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (GlobalFrame != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GlobalFrame);
    }
    size += allClientInput_.CalculateSize(_map_allClientInput_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AllInputData other) {
    if (other == null) {
      return;
    }
    if (other.GlobalFrame != 0) {
      GlobalFrame = other.GlobalFrame;
    }
    allClientInput_.MergeFrom(other.allClientInput_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          GlobalFrame = input.ReadInt32();
          break;
        }
        case 18: {
          allClientInput_.AddEntriesFrom(input, _map_allClientInput_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          GlobalFrame = input.ReadInt32();
          break;
        }
        case 18: {
          allClientInput_.AddEntriesFrom(ref input, _map_allClientInput_codec);
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class InputData : pb::IMessage<InputData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<InputData> _parser = new pb::MessageParser<InputData>(() => new InputData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<InputData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AllInputDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputData(InputData other) : this() {
    id_ = other.id_;
    globalFrame_ = other.globalFrame_;
    axisX_ = other.axisX_;
    axisY_ = other.axisY_;
    action_ = other.action_;
    speed_ = other.speed_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public InputData Clone() {
    return new InputData(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  /// <summary>
  /// 玩家ID
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "global_frame" field.</summary>
  public const int GlobalFrameFieldNumber = 2;
  private int globalFrame_;
  /// <summary>
  /// 帧号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GlobalFrame {
    get { return globalFrame_; }
    set {
      globalFrame_ = value;
    }
  }

  /// <summary>Field number for the "axis_x" field.</summary>
  public const int AxisXFieldNumber = 3;
  private float axisX_;
  /// <summary>
  /// 通用轴 X
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AxisX {
    get { return axisX_; }
    set {
      axisX_ = value;
    }
  }

  /// <summary>Field number for the "axis_y" field.</summary>
  public const int AxisYFieldNumber = 4;
  private float axisY_;
  /// <summary>
  /// 通用轴 Y
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AxisY {
    get { return axisY_; }
    set {
      axisY_ = value;
    }
  }

  /// <summary>Field number for the "action" field.</summary>
  public const int ActionFieldNumber = 5;
  private int action_;
  /// <summary>
  /// 通用动作键 (0:无, 1:A技能, 2:B技能...)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Action {
    get { return action_; }
    set {
      action_ = value;
    }
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 6;
  private float speed_;
  /// <summary>
  /// 可选：如果速度经常变，也可以同步
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Speed {
    get { return speed_; }
    set {
      speed_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as InputData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(InputData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (GlobalFrame != other.GlobalFrame) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AxisX, other.AxisX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AxisY, other.AxisY)) return false;
    if (Action != other.Action) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Speed, other.Speed)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (GlobalFrame != 0) hash ^= GlobalFrame.GetHashCode();
    if (AxisX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AxisX);
    if (AxisY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AxisY);
    if (Action != 0) hash ^= Action.GetHashCode();
    if (Speed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Speed);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (GlobalFrame != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(GlobalFrame);
    }
    if (AxisX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(AxisX);
    }
    if (AxisY != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AxisY);
    }
    if (Action != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Action);
    }
    if (Speed != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (GlobalFrame != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(GlobalFrame);
    }
    if (AxisX != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(AxisX);
    }
    if (AxisY != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AxisY);
    }
    if (Action != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Action);
    }
    if (Speed != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (GlobalFrame != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(GlobalFrame);
    }
    if (AxisX != 0F) {
      size += 1 + 4;
    }
    if (AxisY != 0F) {
      size += 1 + 4;
    }
    if (Action != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Action);
    }
    if (Speed != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(InputData other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.GlobalFrame != 0) {
      GlobalFrame = other.GlobalFrame;
    }
    if (other.AxisX != 0F) {
      AxisX = other.AxisX;
    }
    if (other.AxisY != 0F) {
      AxisY = other.AxisY;
    }
    if (other.Action != 0) {
      Action = other.Action;
    }
    if (other.Speed != 0F) {
      Speed = other.Speed;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 16: {
          GlobalFrame = input.ReadInt32();
          break;
        }
        case 29: {
          AxisX = input.ReadFloat();
          break;
        }
        case 37: {
          AxisY = input.ReadFloat();
          break;
        }
        case 40: {
          Action = input.ReadInt32();
          break;
        }
        case 53: {
          Speed = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 16: {
          GlobalFrame = input.ReadInt32();
          break;
        }
        case 29: {
          AxisX = input.ReadFloat();
          break;
        }
        case 37: {
          AxisY = input.ReadFloat();
          break;
        }
        case 40: {
          Action = input.ReadInt32();
          break;
        }
        case 53: {
          Speed = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
